#pragma config(Motor,  port4,           BigArm,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           WheelMotorR,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           WheelMotorL,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           ClayM,         tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1 ==1)
{


// this is for left motor Straight

if(vexRT[Btn5D]==1)
{
motor[WheelMotorL] = 127;

}
else if(vexRT[Btn5D]==0)
{
motor[WheelMotorL] = 0;
}


// this is for right motor straight


if(vexRT[Btn6D]==1)
{
	motor[WheelMotorR] = 127;
}

else if(vexRT[Btn6D]==0)
{
	motor[WheelMotorR] = 0;
}
// this is for left motor Back

if(vexRT[Btn5U]==1)
{
motor[WheelMotorL] = -127;

}
else if(vexRT[Btn5U]==0)
{
motor[WheelMotorL] = 0;
}



//this is for Right motor Back
if(vexRT[Btn6U]==1)
{
	motor[WheelMotorR] = -127;
}

else if(vexRT[Btn6U]==0)
{
	motor[WheelMotorR] = 0;
	}



	//Big Arm
	if(vexRT[Ch3]==1)
	{
motor[BigArm] = 127;
}


// claw motor

//if(vexRT[Btn6U]==1)
//{
//motor[ClayM] = 50;
//}
//else(vexRT[Btn8D]==1)
//{
//motor[ClayM] = -50;
}
}
